<PlaygroundQuery
  id="Untitled"
  adhocResourceType={null}
  data={null}
  resourceType="restapi"
>
  <RESTQuery
    allowedGroupIds={[]}
    allowedGroups={[]}
    events={[]}
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    queryTimeout="100000"
    retoolVersion="3.116.0"
    watchedParams={[]}
  />
</PlaygroundQuery>
